# Generated by Django 2.0.8 on 2019-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lazylet_term',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='home', max_length=20),
        ),
    ]
