# Generated by Django 2.1.5 on 2019-02-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190119_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordChain_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordChain_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WordChain_Match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='WordChain_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WordChain_Match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WordChain_Player')),
            ],
        ),
        migrations.AddField(
            model_name='wordchain_match',
            name='last_word',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WordChain_Word'),
        ),
    ]
